In [7]:
import numpy as np
import pandas as pd

df=pd.read_excel("XPON_QUALIF(1).xlsx")
df.head()

,ID_LIGNE,ID_CARTE_OLT,NO_PORT,ONU_ID,F_SUSP,ADMIN_STATUS,OPER_STATUS,OLT_POWER_TX,OLT_RX_ONT_POWER,ONU_POWER_TX,ONU_POWER_RX,DESGOUV
0,80190644,63,1,6,0,0,0,NaN,NaN,NaN,NaN,SOUSSE
1,80210544,63,1,6,0,0,0,NaN,NaN,NaN,NaN,SOUSSE
2,80269544,63,1,6,0,0,0,NaN,NaN,NaN,NaN,SOUSSE
3,80290544,63,1,6,0,0,0,NaN,NaN,NaN,NaN,SOUSSE
4,80290944,63,1,6,0,0,0,NaN,NaN,NaN,NaN,SOUSSE

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9002 entries, 0 to 9001
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID_LIGNE          9002 non-null   int64
 1   ID_CARTE_OLT      9002 non-null   int64
 2   NO_PORT           9002 non-null   int64
 3   ONU_ID            9002 non-null   int64
 4   F_SUSP            9002 non-null   int64
 5   ADMIN_STATUS      9002 non-null   int64
 6   OPER_STATUS       9002 non-null   int64
 7   OLT_POWER_TX      6779 non-null   float64
 8   OLT_RX_ONT_POWER  6763 non-null   float64
 9   ONU_POWER_TX      6813 non-null   float64
 10  ONU_POWER_RX      6806 non-null   object
 11  DESGOUV           9002 non-null   object
dtypes: float64(3), int64(7), object(2)
memory usage: 844.1+ KB

In [9]:
isnull = df.isnull()

isnull_count = isnull.sum()

print(isnull_count)

total_isnull = isnull.sum().sum()
print("totals null : ", total_isnull)

ID_LIGNE               0
ID_CARTE_OLT           0
NO_PORT                0
ONU_ID                 0
F_SUSP                 0
ADMIN_STATUS           0
OPER_STATUS            0
OLT_POWER_TX        2223
OLT_RX_ONT_POWER    2239
ONU_POWER_TX        2189
ONU_POWER_RX        2196
DESGOUV                0
dtype: int64
totals null :  8847

In [10]:
df.dropna(inplace=True)

df

,ID_LIGNE,ID_CARTE_OLT,NO_PORT,ONU_ID,F_SUSP,ADMIN_STATUS,OPER_STATUS,OLT_POWER_TX,OLT_RX_ONT_POWER,ONU_POWER_TX,ONU_POWER_RX,DESGOUV
6,80297937,63,1,60,0,1,1,3.4,-20.3,2.364,-19.43,SOUSSE
7,80298937,63,1,60,0,1,1,3.4,-20.3,2.364,-19.43,SOUSSE
8,80387937,63,1,60,0,1,1,3.4,-20.3,2.364,-19.43,SOUSSE
9,80397937,63,1,60,0,1,1,3.4,-20.3,2.364,-19.43,SOUSSE
10,80927937,63,1,60,0,1,1,3.4,-20.3,2.364,-19.43,SOUSSE
...,...,...,...,...,...,...,...,...,...,...,...,...
8997,33828599,170,8,47,0,1,1,3.5,-18.7,2.434,-17.826,BIZERTE
8998,33828600,170,8,48,0,1,1,3.5,-23.0,2.540,-21.488,BIZERTE
8999,33828601,170,8,49,0,1,1,3.7,-22.2,2.272,-19.83,BIZERTE
9000,33828602,170,8,50,0,1,1,3.0,-24.9,2.726,-23.01,BIZERTE
9001,33828603,170,8,51,0,1,1,3.6,-22.1,2.312,-24.436,BIZERTE

In [11]:
doublons = df.duplicated()

doublons_count = doublons.sum()

print(doublons_count)
print(df[doublons])

63
     ID_LIGNE  ID_CARTE_OLT  NO_PORT  ONU_ID  F_SUSP  ADMIN_STATUS  \
34   83109506           101       10       1       0             1
35   83109506           101       10       1       0             1
36   83109506           101       10       1       0             1
37   83109506           101       10       1       0             1
38   83109506           101       10       1       0             1
..        ...           ...      ...     ...     ...           ...
305  85414086           111        7       7       0             1
306  85414086           111        7       7       0             1
307  85414086           111        7       7       0             1
308  85414086           111        7       7       0             1
309  85414086           111        7       7       0             1

     OPER_STATUS  OLT_POWER_TX  OLT_RX_ONT_POWER  ONU_POWER_TX ONU_POWER_RX  \
34             1           3.6             -25.6          2.26      -24.436
35             1           3.6             -25.6          2.26      -24.436
36             1           3.6             -25.6          2.26      -24.436
37             1           3.6             -25.6          2.26      -24.436
38             1           3.6             -25.6          2.26      -24.436
..           ...           ...               ...           ...          ...
305            1           3.7             -21.7          2.27       -18.86
306            1           3.7             -21.7          2.27       -18.86
307            1           3.7             -21.7          2.27       -18.86
308            1           3.7             -21.7          2.27       -18.86
309            1           3.7             -21.7          2.27       -18.86

    DESGOUV
34   SOUSSE
35   SOUSSE
36   SOUSSE
37   SOUSSE
38   SOUSSE
..      ...
305  SOUSSE
306  SOUSSE
307  SOUSSE
308  SOUSSE
309  SOUSSE

[63 rows x 12 columns]

In [12]:
df = df.drop_duplicates()

In [14]:
def etat_valeur(v, low, high):
    if v < low:
        return "faible"
    elif v <= high:
        return "bonne"
    else:
        return "elevee"
df["Etat_OLT_TX"] = df["OLT_POWER_TX"].apply(lambda x: etat_valeur(x, 2, 7))
df["Etat_OLT_RX"] = df["OLT_RX_ONT_POWER"].apply(lambda x: etat_valeur(x, -32, -12))
df["Etat_ONU_TX"] = df["ONU_POWER_TX"].apply(lambda x: etat_valeur(x, 2, 5))
df["Etat_ONU_RX"] = df["ONU_POWER_RX"].apply(lambda x: etat_valeur(x, -28, -7))

C:\Users\mahmo\AppData\Local\Temp\ipykernel_9916\684765312.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Etat_OLT_TX"] = df["OLT_POWER_TX"].apply(lambda x: etat_valeur(x, 2, 7))
C:\Users\mahmo\AppData\Local\Temp\ipykernel_9916\684765312.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Etat_OLT_RX"] = df["OLT_RX_ONT_POWER"].apply(lambda x: etat_valeur(x, -32, -12))
C:\Users\mahmo\AppData\Local\Temp\ipykernel_9916\684765312.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Etat_ONU_TX"] = df["ONU_POWER_TX"].apply(lambda x: etat_valeur(x, 2, 5))
C:\Users\mahmo\AppData\Local\Temp\ipykernel_9916\684765312.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Etat_ONU_RX"] = df["ONU_POWER_RX"].apply(lambda x: etat_valeur(x, -28, -7))

In [15]:
def etat_global(row):
    if "faible" in row.values:
        return "anomalie"
    return "normal"

df["Anomalie_technique"] = df[
    ["Etat_OLT_TX","Etat_OLT_RX","Etat_ONU_TX","Etat_ONU_RX"]
].apply(etat_global, axis=1)

C:\Users\mahmo\AppData\Local\Temp\ipykernel_9916\1432877201.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Anomalie_technique"] = df[

In [16]:

df["Anomalie_admin"] = np.where(
    (df["F_SUSP"] == 1) & (df["ADMIN_STATUS"] == 1),
    "Anomalie",
    "Normal"
)

C:\Users\mahmo\AppData\Local\Temp\ipykernel_9916\2350335469.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Anomalie_admin"] = np.where(

In [23]:

df["Anomalie"] = np.where(
    (df["Anomalie_technique"] == "anomalie") | (df["Anomalie_admin"] == "anomalie"),
    "Anomalie",
    "Normal"
)

C:\Users\mahmo\AppData\Local\Temp\ipykernel_9916\590486447.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Anomalie"] = np.where(

In [24]:
df.to_excel("dataset_visu.xlsx",index=False)